from fpdf import FPDF
from calculator import calculate_sgpa, calculate_cgpa, sgpa_to_percentage, get_class, get_backlogs
import os

class ResultPDF(FPDF):
    def header(self):
        self.set_fill_color(30, 30, 46)
        self.rect(0, 0, 210, 297, 'F')
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(137, 180, 250)
        self.cell(0, 15, 'JNTUK Academic Result Report', ln=True, align='C')
        self.set_font('Helvetica', '', 11)
        self.set_text_color(180, 180, 180)
        self.cell(0, 8, 'Generated by JNTUK CGPA Analyzer', ln=True, align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')


def export_pdf(student_info, semesters):
    pdf = ResultPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Student Info
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(166, 227, 161)
    pdf.cell(0, 10, 'Student Information', ln=True)
    pdf.set_draw_color(166, 227, 161)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(220, 220, 220)
    info_items = [
        ('Name', student_info.get('name', 'N/A')),
        ('Roll Number', student_info.get('roll', 'N/A')),
        ('Branch', student_info.get('branch', 'N/A')),
        ('College', student_info.get('college', 'N/A')),
    ]
    for label, value in info_items:
        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(137, 180, 250)
        pdf.cell(45, 8, f'{label}:', ln=False)
        pdf.set_font('Helvetica', '', 11)
        pdf.set_text_color(220, 220, 220)
        pdf.cell(0, 8, value, ln=True)

    pdf.ln(5)

    # Overall Summary
    cgpa = calculate_cgpa(semesters)
    percentage = sgpa_to_percentage(cgpa)
    degree_class = get_class(cgpa)
    backlogs = get_backlogs(semesters)

    # Remove emojis from degree class
    import re
    degree_class = re.sub(r'[^\x00-\x7F]+', '', degree_class).strip()

    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(166, 227, 161)
    pdf.cell(0, 10, 'Overall Academic Summary', ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    summary_items = [
        ('Overall CGPA', str(cgpa)),
        ('Equivalent Percentage', f'{percentage}%'),
        ('Degree Class', degree_class),
        ('Total Backlogs', str(len(backlogs))),
    ]
    for label, value in summary_items:
        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(137, 180, 250)
        pdf.cell(60, 8, f'{label}:', ln=False)
        pdf.set_font('Helvetica', '', 11)
        pdf.set_text_color(220, 220, 220)
        pdf.cell(0, 8, value, ln=True)

    pdf.ln(5)

    # Semester wise Results
    for sem in semesters:
        sgpa = calculate_sgpa(sem['subjects'])
        percentage = sgpa_to_percentage(sgpa)

        pdf.set_font('Helvetica', 'B', 13)
        pdf.set_text_color(250, 179, 135)
        pdf.cell(0, 10, f"Semester {sem['semester']}", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(2)

        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(137, 180, 250)
        pdf.cell(60, 8, f'SGPA: {sgpa}', ln=False)
        pdf.cell(0, 8, f'Percentage: {percentage}%', ln=True)
        pdf.ln(2)

        # Table header
        pdf.set_fill_color(49, 50, 68)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(80, 8, 'Subject', border=0, fill=True)
        pdf.cell(25, 8, 'Credits', border=0, fill=True, align='C')
        pdf.cell(25, 8, 'Grade', border=0, fill=True, align='C')
        pdf.cell(25, 8, 'Points', border=0, fill=True, align='C')
        pdf.cell(0, 8, 'Status', border=0, fill=True, align='C', ln=True)

        # Table rows
        pdf.set_font('Helvetica', '', 10)
        for i, sub in enumerate(sem['subjects']):
            from calculator import get_grade
            gp = get_grade(sub['grade'])
            status = 'Pass' if sub['grade'].upper() != 'F' else 'Fail'
            fill = i % 2 == 0
            if fill:
                pdf.set_fill_color(40, 40, 56)
            else:
                pdf.set_fill_color(30, 30, 46)

            if sub['grade'].upper() == 'F':
                pdf.set_text_color(243, 139, 168)
            else:
                pdf.set_text_color(220, 220, 220)

            pdf.cell(80, 7, sub['name'][:35], border=0, fill=True)
            pdf.cell(25, 7, str(sub['credits']), border=0, fill=True, align='C')
            pdf.cell(25, 7, sub['grade'].upper(), border=0, fill=True, align='C')
            pdf.cell(25, 7, str(gp), border=0, fill=True, align='C')
            pdf.cell(0, 7, status, border=0, fill=True, align='C', ln=True)

        pdf.ln(5)

    # Backlogs Section
    if backlogs:
        pdf.set_font('Helvetica', 'B', 13)
        pdf.set_text_color(243, 139, 168)
        pdf.cell(0, 10, 'Backlog Subjects', ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_fill_color(49, 50, 68)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(20, 8, 'Sem', border=0, fill=True, align='C')
        pdf.cell(120, 8, 'Subject', border=0, fill=True)
        pdf.cell(0, 8, 'Credits', border=0, fill=True, align='C', ln=True)

        pdf.set_font('Helvetica', '', 10)
        for b in backlogs:
            pdf.set_text_color(243, 139, 168)
            pdf.set_fill_color(40, 40, 56)
            pdf.cell(20, 7, str(b['semester']), border=0, fill=True, align='C')
            pdf.cell(120, 7, b['subject'], border=0, fill=True)
            pdf.cell(0, 7, str(b['credits']), border=0, fill=True, align='C', ln=True)
        pdf.ln(5)

    # Charts
    charts = [
        ('sgpa_chart.png', 'Semester wise SGPA Chart'),
        ('cgpa_progress.png', 'CGPA Progress Chart'),
    ]
    for chart_file, chart_title in charts:
        if os.path.exists(chart_file):
            pdf.add_page()
            pdf.set_font('Helvetica', 'B', 13)
            pdf.set_text_color(166, 227, 161)
            pdf.cell(0, 10, chart_title, ln=True, align='C')
            pdf.image(chart_file, x=10, w=190)

    # Save
    filename = f"Result_{student_info.get('roll', 'student')}.pdf"
    pdf.output(filename)
    print(f"\nPDF Report saved as {filename}")
    return filename